project:
  type: website
  output-dir: docs

website:
  title: "HyeonggeunChoe"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual





