---
title: "Research"
---

## Research Interests

Policing; Gun and Group Violence; Crime and Place; Causal Inference

## Manuscripts Under Review

### Gang Takedowns and Neighborhood Violence: Evidence from a Case Study in Philadelphia

**Hyeonggeun Choe**, Alyssa Mendlein, and Aaron Chalfin\
*Criminology & Public Policy*, minor revision.

[Paper](#) \| [Abstract](#)

### The Minimal Effects of Body-Worn Camera Adoption on Organizational Outcomes

**Hyeonggeun Choe** and Charles Loeffler\
Submitted.

### Police Traffic Stops: Bias or Public Safety Tool? A Spatial Analysis of Philadelphia

Sungil Han and **Hyeonggeun Choe**\
Submitted.

## Working Papers

### The Local Effects of Federal Firearms Licensees on Gun Violence

**Hyeonggeun Choe**

### Reassessing the Effect of Body-Worn Camera Adoption on Police Violence

**Hyeonggeun Choe**

### Recreational Cannabis Legalization, Marijuana-Positive Traffic Fatalities, and Cross-Border Effects in the Mid-Atlantic United States

Jordan Hyatt, Nathan Link, and **Hyeonggeun Choe**

## Works in Progress

### The Effect of Gas Stations on Local Crime: Evidence from Chicago

**Hyeonggeun Choe** and Sinui Park

## Peer-Reviewed Publications

### Insights from U.S. D.A.R.E. and Alternative Youth Drug Prevention Programs: Implications for Korea

**Hyeonggeun Choe** and J. Lee (2026)\
*Korean Association of Addiction Crime Review*, 16(2).

### A Study on the Factors Affecting Crime Increase Perception toward Foreigners

**Hyeonggeun Choe**, S. Lee, and H. Jang (2022)\
*The Korean Association for Terrorism Studies*, 15(4).

### A Test of the Non-Linear Relationship between Collective Efficacy and Fear of Crime in the Context of South Korea

S. Park, **Hyeonggeun Choe**, and E. Hwang (2022)\
*Journal of Korean Criminological Association*, 16(2).

### The Difference of the Level and Factors of Fear of Crime between Single-Person and Multi-Person Households: Focusing on the Trend of Fear of Crime over Time

**Hyeonggeun Choe**, S. Park, J. Han, D. Min, N. Kim, and E. Hwang (2021)\
*Journal of Korean Criminological Association*, 15(3).
